spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=null

# To initialize schema automatically
spring.sql.init.mode=always
spring.r2dbc.properties.quoteIdentifiers=false

logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.pattern.level=%5p [${spring.application.name:},%X{correlationId}]

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.endpoints.web.exposure.include=*
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

resilience4j.circuitbreaker.instances.userService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.userService.timeoutDuration=2s
resilience4j.bulkhead.instances.userService.maxConcurrentCalls=10

resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=500ms
resilience4j.retry.instances.userService.enableExponentialBackoff=true
resilience4j.retry.instances.userService.exponentialBackoffMultiplier=2
resilience4j.retry.instances.userService.enableRandomizedWait=true
resilience4j.retry.instances.userService.randomizedWaitFactor=0.5
resilience4j.retry.instances.userService.retryExceptions=java.io.IOException, java.util.concurrent.TimeoutException
resilience4j.retry.instances.userService.ignoreExceptions=java.lang.IllegalArgumentException

resilience4j.circuitbreaker.instances.orderService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.orderService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderService.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.orderService.timeoutDuration=2s
resilience4j.bulkhead.instances.orderService.maxConcurrentCalls=10

resilience4j.circuitbreaker.instances.recommendationService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.recommendationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.recommendationService.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.recommendationService.timeoutDuration=2s
resilience4j.bulkhead.instances.recommendationService.maxConcurrentCalls=10