spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=null

# To initialize schema automatically
spring.sql.init.mode=always
spring.r2dbc.properties.quoteIdentifiers=false


logging.level.org.springframework.r2dbc=DEBUG
logging.pattern.level=%5p [${spring.application.name:},%X{correlationId}]

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
